//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Racunala
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graficka_Kartica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Graficka_Kartica()
        {
            this.Konfiguracije_Racunala = new HashSet<Konfiguracije_Racunala>();
        }
    
        public int Id_Graficke { get; set; }
        public string Naziv__Graficke { get; set; }
        public Nullable<int> Godina_Proizvodnje { get; set; }
        public string Naziv_Proizvodaca { get; set; }
        public string Kapacitet_Memorije { get; set; }
        public Nullable<decimal> Cijena_Graficke { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konfiguracije_Racunala> Konfiguracije_Racunala { get; set; }
    }
}
