//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Racunala
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RacunalaEntities : DbContext
    {
        public RacunalaEntities()
            : base("name=RacunalaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kuciste> Graficka_Kartica { get; set; }
        public virtual DbSet<Konfiguracije_Racunala> Konfiguracije_Racunala { get; set; }
        public virtual DbSet<Kuciste> Kucistes { get; set; }
        public virtual DbSet<Maticna_Ploca> Maticna_Ploca { get; set; }
        public virtual DbSet<Napajanje> Napajanjes { get; set; }
        public virtual DbSet<Pohrana> Pohranas { get; set; }
        public virtual DbSet<Procesor> Procesors { get; set; }
        public virtual DbSet<Radna_Memorija> Radna_Memorija { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
