//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Racunala
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skladiste
    {
        public int Vk_Konfiguracija { get; set; }
        public Nullable<int> Trenutno_Stanje { get; set; }
        public Nullable<int> Staro_Stanje { get; set; }
        public Nullable<System.DateTime> Datum_evidencije { get; set; }
        public string Pozicija { get; set; }
    
        public virtual Konfiguracije_Racunala Konfiguracije_Racunala { get; set; }
    }
}
